import AppFooter from "./components/AppFooter";
import AppHeader from "./components/AppHeader";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="winter">
      <body className="flex flex-col min-h-screen bg-base-100">
        <AppHeader />
        <div className="flex-grow">
          <main>{children}</main>
        </div>
        <AppFooter />
      </body>
    </html>
  );
}
